edit: floatadd.o
	g++ floatadd.o  -o floatadd
	rm *.o
	mv floatadd.exe ../ExeFile
	../ExeFile/floatadd.exe
floatadd.o : floatadd.cpp
	g++ -c floatadd.cpp 
clean:
	rm *.o
move:
	mv floatadd.exe ../ExeFile
