edit: template_array171009.o
	g++ template_array171009.o  -o template_array171009
	rm *.o
	mv template_array171009.exe ../ExeFile
	../ExeFile/template_array171009.exe
template_array171009.o : template_array171009.cpp
	g++ -c template_array171009.cpp 
clean:
	rm *.o
move:
	mv template_array171009.exe ../ExeFile
