edit: template_function.o
	g++ template_function.o  -o template_function
	rm *.o
	mv template_function.exe ../ExeFile
	../ExeFile/template_function.exe
template_function.o : template_function.cpp
	g++ -c template_function.cpp 
clean:
	rm *.o
move:
	mv template_function.exe ../ExeFile
